### ISSUE TITLE
Protobufs

### ISSUE THREAD

**Issue by goldbattle** [tjhorner/pokemon-go-server#1]
Have you been able to successfully decode the protobufs, I can't get that far on them.

I just know that first it communicated with:
`https://pgorelease.nianticlabs.com/plfe`

Then gets a number from it some how:
`https://pgorelease.nianticlabs.com/plfe/120`

And then all active talk is through the RPC endpoint:
`https://pgorelease.nianticlabs.com/plfe/120/rpc`

**Comment by tjhorner** [comment]
Not quite yet, but a couple of people have contacted me and we are working on decoding the game's protobuf descriptor.

**Comment by goldbattle** [comment]
I tried looking through the `libNianticLabsPlugin.so` decompiled code and
running a few programs on it [1], and didn't pull up anything.

[1]  https://github.com/sysdream/Protod

**Comment by tjhorner** [comment]
I don't think it would be there, @bettse found a decompiled iOS version [over here](https://github.com/rpplusplus/PokemonHook) and found a big list of proto files embedded within, but we can't seem to extract them with Protod.

I've created a Gitter room if you want to discuss this further: https://gitter.im/tjhorner/pokemon-go-server

**Comment by carpikes** [comment]
hi! where is the list of proto files? i can't find it :(

**Comment by tjhorner** [comment]
Nowhere at the moment. We're currently looking for a way to extract them
from the decompiled game files. In the meantime, you can join the gitter
linked above.

**Comment by goldbattle** [comment]
Most protos can be found here:
https://github.com/AeonLucid/POGOProtos

With already compiled version here:
- NodeJS - https://github.com/rastapasta/node-pokemongo-protobuf
- .NET - https://github.com/johnduhart/POGOProtos-dotnet
- PHP - https://github.com/jaspervdm/pogoprotos-php
- Go - https://github.com/zeeraw/pogo-protos
