### ISSUE TITLE
Configure Fiddler to get this server working

### ISSUE THREAD

**Issue by y3nd** [tjhorner/pokemon-go-server#4]
Hi!
I'm trying to configure Fiddler to redirect traffic to this server but it isn't working.
I tried to configure the "Gateway" thing to the server without success.
What should I do to get this working ?
Thx a lot

**Comment by tjhorner** [comment]
Go to Tools -> Telerik Fiddler Settings and set these options:

![image](https://cloud.githubusercontent.com/assets/2646487/17279460/f79b8fd4-5728-11e6-92c8-19a0bb7de8ee.png)

![image](https://cloud.githubusercontent.com/assets/2646487/17279462/fc130a56-5728-11e6-9fdc-34c7abaea768.png)

Then click "Actions" in the HTTPS settings menu, export the root certificate to your desktop

![image](https://cloud.githubusercontent.com/assets/2646487/17279464/0ab1091e-5729-11e6-84d1-d29e3f6eb828.png)

Transfer that to your phone somehow and trust it as a root certificate.

Now go to the AutoResponder tab and make it look like this:

![image](https://cloud.githubusercontent.com/assets/2646487/17279469/241c1998-5729-11e6-9b44-782585199743.png)

**Comment by y3nd** [comment]
Thanks a lot!

Now the traffic is successfully redirected and the login seems to work **until the game data recovering process**. I get :

```
{ status_code: 2,
  request_id: Long { low: 22, high: 579833852, unsigned: true },
  requests:
   [ { request_type: 6, request_message: [Object] },
     { request_type: 126, request_message: [Object] },
     { request_type: 4, request_message: [Object] },
     { request_type: 129, request_message: [Object] },
     { request_type: 5, request_message: [Object] } ],
  unknown6: [ { request_type: 6, unknown2: [Object] } ],
  latitude: 43.1X,
  longitude: 5.8X,
  altitude: 20,
  auth_info: null,
  auth_ticket:
   { start:
      { buffer: <Buffer 08 02 18 96 80 80 80 c0 ff e3 c7 22 22 02 08 06 22 02 08 7e 22 02 08 04 22 03 08 81 01 22 02 08 05 32 a8 0e 08 06 12 a3 0e 0a a0 0e 64 b5 25 d9 af af ... >,
        offset: 1899,
        markedOffset: -1,
        limit: 1918,
        littleEndian: true,
        noAssert: false },
     expire_timestamp_ms: Long { low: 1316134911, high: 2328, unsigned: true },
     end:
      { buffer: <Buffer 08 02 18 96 80 80 80 c0 ff e3 c7 22 22 02 08 06 22 02 08 7e 22 02 08 04 22 03 08 81 01 22 02 08 05 32 a8 0e 08 06 12 a3 0e 0a a0 0e 64 b5 25 d9 af af ... >,
        offset: 1928,
        markedOffset: -1,
        limit: 1951,
        littleEndian: true,
        noAssert: false } },
  unknown12: Long { low: 957, high: 0, unsigned: false } }
Got a request
{ status_code: 2,
  request_id: Long { low: 22, high: 579833852, unsigned: true },
  requests:
   [ { request_type: 6, request_message: [Object] },
     { request_type: 126, request_message: [Object] },
     { request_type: 4, request_message: [Object] },
     { request_type: 129, request_message: [Object] },
     { request_type: 5, request_message: [Object] } ],
  unknown6: [ { request_type: 6, unknown2: [Object] } ],
  latitude: 43.1X,
  longitude: 5.8X,
  altitude: 20,
  auth_info: null,
  auth_ticket:
   { start:
      { buffer: <Buffer 08 02 18 96 80 80 80 c0 ff e3 c7 22 22 02 08 06 22 02 08 7e 22 02 08 04 22 03 08 81 01 22 02 08 05 32 a8 0e 08 06 12 a3 0e 0a a0 0e 64 b5 25 d9 af af ... >,
        offset: 1899,
        markedOffset: -1,
        limit: 1918,
        littleEndian: true,
        noAssert: false },
     expire_timestamp_ms: Long { low: 1316134911, high: 2328, unsigned: true },
     end:
      { buffer: <Buffer 08 02 18 96 80 80 80 c0 ff e3 c7 22 22 02 08 06 22 02 08 7e 22 02 08 04 22 03 08 81 01 22 02 08 05 32 a8 0e 08 06 12 a3 0e 0a a0 0e 64 b5 25 d9 af af ... >,
        offset: 1928,
        markedOffset: -1,
        limit: 1951,
        littleEndian: true,
        noAssert: false } },
  unknown12: Long { low: 957, high: 0, unsigned: false } }
Received RPC call with these requests: 6, 126, 4, 129, 5
UNKNOWN REQUEST! 6
```

And the app show me the box with the "Retry" button.
I don't know if it's directly linked to the login crash.

I've tried on 0.29.0 & 0.29.3 with Google and PTC but it keeps crashing :(
The code wasn't modified

Maybe i'm missing something...

**Comment by tjhorner** [comment]
Since the game was recently updated, they maybe changed the protocol schema up a bit. I'll check it out, thanks for reporting 😅

**Comment by tjhorner** [comment]
Okay, so I found the cause. The server doesn't know how to respond to request `6`, which is defined here: https://github.com/tjhorner/pokemon-go-server/blob/master/POGOProtos/Networking/Requests/RequestType.proto#L13

Have you used the app _before_ connecting to this custom server? Right now, it doesn't support the item templates. In a later update, I'll make it forward all unknown requests to the actual Pokemon GO servers, but for now you'll need to run it on the actual servers at least once.

**Comment by y3nd** [comment]
I'm wiping all the data of the app before testing but it's not working too, even with a new unused account :/
The client always request the "6 request" during the login

**Comment by tjhorner** [comment]
Nonono don't wipe the data! Sign in without using this server first, then close the app, connect to this server and try again.
